# Generated by Django 6.0.6 on 2026-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='codigo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
